/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.otus;

import ru.otus.greeting.HelloOtus;

public class App {
    public static void main(String... args) {
        HelloOtus helloOtus = new HelloOtus();
        helloOtus.sayHello();
    }
}
